<?php

declare(strict_types=1);

/*
 * This file is part of the JUHE Contao OpenAI Assistant bundle.
 *
 * (c) JUHE IT-solutions
 *
 * @license LGPL-3.0-or-later
 */

namespace JuheItSolutions\ContaoOpenaiAssistant\Tests\Controller;

use JuheItSolutions\ContaoOpenaiAssistant\Controller\FrontendModule\AiChatModuleController;
use PHPUnit\Framework\TestCase;

/**
 * Guards the fix for hard-coded chat endpoints, which made the widget fail on any
 * installation served from a subdirectory (https://example.com/cms/).
 *
 * These are source-level assertions on purpose: exercising the module controller
 * for real would need the Contao framework, a FragmentTemplate and a container,
 * which would test Contao rather than this rule. The rule itself is simple - no
 * absolute chat path may be written by hand - and that is exactly what is checked.
 */
class AiChatEndpointUrlTest extends TestCase
{
    public function testTheModuleControllerGeneratesEndpointsInsteadOfHardCodingThem(): void
    {
        $source = $this->readSource((new \ReflectionClass(AiChatModuleController::class))->getFileName());

        $this->assertStringNotContainsString(
            "'/ai-chat/",
            $source,
            'Chat endpoints must come from the router, or a subdirectory installation calls the domain root.',
        );

        foreach (['ai_chat_send', 'ai_chat_token', 'ai_chat_history'] as $route) {
            $this->assertStringContainsString(
                "generate('".$route."')",
                $source,
                \sprintf('Route %s should be generated by the router.', $route),
            );
        }
    }

    /**
     * The three literals left in the JavaScript are deliberate fallbacks for chat
     * templates copied from an older version, which do not carry the data
     * attributes. Each one must sit behind a "||" so a missing attribute is the
     * only way to reach it.
     */
    public function testTheJavaScriptOnlyKeepsDocumentedFallbacks(): void
    {
        $js = $this->readSource(__DIR__.'/../../public/js/ai-chat.js');

        foreach (preg_split('/\R/', $js) ?: [] as $number => $line) {
            if (!str_contains($line, "'/ai-chat/")) {
                continue;
            }

            $this->assertStringContainsString(
                '||',
                $line,
                \sprintf('ai-chat.js line %d hard-codes a chat path outside a fallback.', $number + 1),
            );
        }

        $this->assertSame(
            3,
            substr_count($js, "'/ai-chat/"),
            'Expected exactly three fallbacks (send, token, history).',
        );
    }

    private function readSource(string|false $path): string
    {
        $this->assertIsString($path);
        $this->assertFileExists($path);

        return (string) file_get_contents($path);
    }
}
