name: CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, xml, ctype, iconv, intl, curl, json, dom, gd

    - name: Validate composer.json
      run: composer validate

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php-8.2-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.2-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check PHP syntax
      run: |
        find src/ -name "*.php" -exec php -l {} \;

    - name: Check code style
      run: vendor/bin/ecs check

    - name: Run PHPStan analysis
      run: vendor/bin/phpstan analyse src/ --level=5

  code-formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, xml, ctype, iconv, intl, dom

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Format code
      run: vendor/bin/ecs check --fix

    - name: Check if formatting changed files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Code formatting issues found. Please run 'vendor/bin/ecs check --fix' locally."
          git diff
          exit 1
        fi

  security:
    name: Security Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run security check
      run: composer audit --format=json 2>/dev/null || echo "Security check skipped (composer audit not available)" 