name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, xml, ctype, iconv, intl, dom

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Validate composer.json
      run: composer validate

    - name: Check PHP syntax
      run: |
        find src/ -name "*.php" -exec php -l {} \;

    - name: Check code style
      run: vendor/bin/ecs check

    - name: Run PHPStan analysis
      run: vendor/bin/phpstan analyse src/ --level=5

    - name: Run security check
      run: composer audit --format=json 2>/dev/null || echo "Security check skipped (composer audit not available)"

    - name: Derive release display name
      id: derive_release
      run: echo "release_name=Version ${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ steps.derive_release.outputs.release_name }}
        body: |
          ## 🎉 Release ${{ github.ref_name }}
          
          ### ✅ Quality Checks Passed
          - PHP syntax validation
          - Code style compliance (ECS)
          - Static analysis (PHPStan Level 5)
          - Security vulnerability scan
          - Composer validation
          
          ### 📦 Installation
          ```bash
          composer require juhe-it-solutions/contao-openai-assistant
          ```
          
          ### 🔗 Links
          - [Documentation](https://github.com/juhe-it-solutions/contao-openai-assistant/tree/main/docs)
          - [Security Policy](https://github.com/juhe-it-solutions/contao-openai-assistant/blob/main/SECURITY.md)
          - [Changelog](https://github.com/juhe-it-solutions/contao-openai-assistant/blob/main/CHANGELOG.md)
        draft: false
        prerelease: false 